use linkscope_core::{engine::Engine,graph::Graph,model::*,network::{validate_route,Route},storage::Store,transform::{parse,Manifest},vault::Vault};
use std::io::Write;
fn fixture()->Batch{let a=Node::new("domain","Example.org.","test-a");let b=Node::new("ip","192.0.2.1","test-a");let e=Edge::new(&a.id,&b.id,"resolves-to","test-a");Batch{nodes:vec![a,b],edges:vec![e]}}
#[test]fn deterministic_identity(){assert_eq!(Node::new("domain","EXAMPLE.ORG.","a").id,Node::new("domain","example.org","b").id);}
#[test]fn dangling_edges_rejected_before_mutation(){let mut graph=Graph::new(1024*1024,true);let mut batch=fixture();batch.nodes.pop();assert!(graph.admit(&batch).is_err());assert_eq!(graph.topology.node_count(),0);}
#[test]fn memory_admission_fails_without_oom(){let mut graph=Graph::new(64,true);assert!(graph.admit(&fixture()).is_err());assert_eq!(graph.topology.node_count(),0);}
#[test]fn duplicate_batches_are_idempotent(){let mut e=Engine::open(None,8*1024*1024).unwrap();e.apply(fixture()).unwrap();e.apply(fixture()).unwrap();assert_eq!(e.graph.topology.node_count(),2);assert_eq!(e.graph.topology.edge_count(),1);assert_eq!(e.search("example").unwrap().len(),1);}
#[test]fn log_recovers_lost_sqlite_and_truncates_incomplete_tail(){let dir=tempfile::tempdir().unwrap();{let mut s=Store::open(Some(dir.path())).unwrap();s.commit(&fixture()).unwrap();}std::fs::remove_file(dir.path().join("graph.sqlite")).unwrap();{let mut f=std::fs::OpenOptions::new().append(true).open(dir.path().join("transactions.jsonl")).unwrap();f.write_all(b"{\"id\":\"partial").unwrap();}let s=Store::open(Some(dir.path())).unwrap();assert_eq!(s.page("nodes",0,512).unwrap().len(),2);assert_eq!(s.page("edges",0,512).unwrap().len(),1);assert_eq!(std::fs::read(dir.path().join("transactions.jsonl")).unwrap().last(),Some(&b'\n'));}
#[test]fn corrupt_complete_log_stops_recovery(){let dir=tempfile::tempdir().unwrap();std::fs::write(dir.path().join("transactions.jsonl"),b"{bad json}\n").unwrap();assert!(Store::open(Some(dir.path())).is_err());}
#[test]fn cache_expired_entries_are_not_returned(){let mut s=Store::open(None).unwrap();s.cache_put("key",b"value",60).unwrap();assert_eq!(s.cache_get("key").unwrap(),Some(b"value".to_vec()));s.db.execute("UPDATE cache SET expires=0",[]).unwrap();assert!(s.cache_get("key").unwrap().is_none());}
#[test]fn anonymity_policy_fails_closed(){assert!(validate_route(&Route::Offline,true).is_ok());assert!(validate_route(&Route::DirectDoh{resolver:"cloudflare".into()},true).is_err());for u in ["socks5://127.0.0.1:9050","socks5h://proxy.example:9050","http://user:pass@127.0.0.1:8080"]{assert!(validate_route(&Route::Proxy{url:u.into()},true).is_err());}assert!(validate_route(&Route::Proxy{url:"socks5h://127.0.0.1:9050".into()},true).is_ok());assert!(validate_route(&Route::Tor,true).is_err());}
#[test]fn cold_payloads_can_be_loaded_from_store(){let mut e=Engine::open(None,1024*1024).unwrap();let n=fixture().nodes[0].clone();e.apply(fixture()).unwrap();let i=e.graph.ids[&n.id];e.graph.topology[i].payload=None;assert_eq!(e.node(&n.id).unwrap().unwrap().value,n.value);}
#[test]fn parser_ignores_invalid_dns_addresses(){let m=Manifest{id:"dns".into(),name:"DNS".into(),input:"domain".into(),group:"data".into(),endpoint:"https://dns.google/resolve?name={value}".into(),host:"dns.google".into(),parser:"doh".into(),pointer:String::new(),output_kind:String::new(),ttl:60};let b=parse(&m,&Node::new("domain","example.org","test"),br#"{"Answer":[{"type":1,"data":"192.0.2.1"},{"type":1,"data":"not an ip"}]}"#).unwrap();assert_eq!(b.nodes.len(),2);assert_eq!(b.edges.len(),1);}
#[test]fn exports_preserve_special_characters_and_references(){let mut store=Store::open(None).unwrap();store.commit(&fixture()).unwrap();for format in ["json","stix","misp"]{let mut bytes=Vec::new();linkscope_core::export::write(&store,format,&mut bytes).unwrap();let value:serde_json::Value=serde_json::from_slice(&bytes).unwrap();assert!(value.is_object());}let mut xml=Vec::new();linkscope_core::export::write(&store,"graphml",&mut xml).unwrap();assert!(String::from_utf8(xml).unwrap().contains("edgedefault=\"directed\""));}
#[test]fn vault_roundtrip_wrong_passphrase_and_replacement(){let dir=tempfile::tempdir().unwrap();let path=dir.path().join("keys.age");let mut a=Vault::default();a.set("source".into(),"test-secret".into());a.save(&path,zeroize::Zeroizing::new("correct horse battery staple".into())).unwrap();assert!(!String::from_utf8_lossy(&std::fs::read(&path).unwrap()).contains("test-secret"));let mut b=Vault::default();assert!(b.unlock(&path,zeroize::Zeroizing::new("incorrect passphrase".into())).is_err());b.unlock(&path,zeroize::Zeroizing::new("correct horse battery staple".into())).unwrap();assert_eq!(b.get("source").unwrap().as_str(),"test-secret");b.save(&path,zeroize::Zeroizing::new("another long password".into())).unwrap();b.lock();assert!(b.get("source").is_none());}
