import {GraphModel,synthetic,colors,confidenceNames,timeRange,convexHull} from './model.js';
import {Renderer} from './renderer.js';
import {FallbackRenderer} from './fallback-renderer.js';
const $=id=>document.getElementById(id),desktop=!!window.__TAURI__,invoke=desktop?window.__TAURI__.core.invoke:null;
let model=new GraphModel(),selected=-1,demo=false,manifests=[],config={memory_mb:512,network:{anonymous:true,default_route:{mode:'offline'},sources:{}}},running=false,hulls=false,searchSeq=0,currentQuery='',toastTimer,worker,loadVersion=0,view='graph',clusterVersion=0;
const kindLabels={domain:'Домены',ip:'IP-адреса',username:'Профили',url:'URL',email:'Email'};
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,7000)}
function log(text,error=false){const el=document.createElement('div');el.className='activity-row'+(error?' error':'');el.textContent=text;$('activity').prepend(el);while($('activity').children.length>40)$('activity').lastChild.remove()}
function safe(fn){return(...args)=>Promise.resolve().then(()=>fn(...args)).catch(e=>{toast(String(e.message||e));log(String(e.message||e),true)})}
function button(text,fn,cls=''){const b=document.createElement('button');b.textContent=text;b.className=cls;b.onclick=safe(fn);return b}
let renderer;
try{renderer=new Renderer($('graph'),state=>{if(state.error)toast(state.error);if('fps'in state)$('fps').textContent=state.idle?'IDLE · on demand':`${state.fps.toFixed(0)} FPS`;if(state.layoutDone){drawOverlay();savePositions().catch(e=>toast(String(e)));}})}catch(e){const reason=String(e.message||e);renderer=new FallbackRenderer($('graph'),reason);toast(`Граф недоступен: ${reason}`);$('status').textContent='Граф недоступен · безопасный режим';$('layout').disabled=true;$('layout').title='GPU layout requires WebGL2';log(`Renderer startup failed: ${reason}`,true)}
function updateCounts(){const count=model.nodes.length;$('counts').textContent=`${count.toLocaleString()} nodes   ·   ${model.edges.length.toLocaleString()} edges`;$('entity-count').textContent=count.toLocaleString();$('empty').hidden=count>0;$('kinds').replaceChildren();for(const[k,label]of Object.entries(kindLabels)){const n=model.nodes.reduce((n,v)=>n+Number(v.kind===k),0),row=document.createElement('div');row.className='kind-row';const dot=document.createElement('span');dot.className='kind-dot';dot.style.background=`rgb(${colors[k].map(v=>v*255).join(',')})`;row.append(dot,document.createTextNode(label));const c=document.createElement('small');c.textContent=n.toLocaleString();row.append(c);$('kinds').append(row)}$('mode-label').textContent=demo?'SYNTHETIC':desktop?'DESKTOP':'BROWSER PREVIEW';$('graph-note').textContent=renderer.disabled?'GPU недоступен · безопасный режим':demo?'Синтетические данные · без сетевых запросов':'WebGL2 · локальный граф';}
function refresh(active=[],fit=false){renderer.setModel(model,active);updateCounts();if(fit)renderer.fit();applyTime();drawOverlay();if(view==='map')drawMap();}
function drawOverlay(){const c=$('overlay'),r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,1.5);c.width=r.width*d;c.height=r.height*d;const ctx=c.getContext('2d');ctx.scale(d,d);if(!model.nodes.length)return;
 if(renderer.disabled){
  ctx.strokeStyle='rgba(86,129,182,.27)';ctx.lineWidth=1;ctx.beginPath();let drawn=0;
  for(const edge of model.edges){if(drawn++>=5000)break;const a=model.nodes[edge.a],b=model.nodes[edge.b];if(!a||!b||a.timestamp<renderer.timeRange[0]||a.timestamp>renderer.timeRange[1]||b.timestamp<renderer.timeRange[0]||b.timestamp>renderer.timeRange[1])continue;const[x1,y1]=renderer.screen(edge.a),[x2,y2]=renderer.screen(edge.b);ctx.moveTo(x1,y1);ctx.lineTo(x2,y2)}ctx.stroke();
  for(let i=0;i<Math.min(model.nodes.length,3000);i++){const n=model.nodes[i];if(n.timestamp<renderer.timeRange[0]||n.timestamp>renderer.timeRange[1])continue;const[x,y]=renderer.screen(i);ctx.fillStyle=i===selected?'#fce8a6':'#84aaed';ctx.beginPath();ctx.arc(x,y,i===selected?6:3,0,Math.PI*2);ctx.fill()}
 }
 
 if(hulls&&renderer.layoutSteps===0){const groups=new Map();model.nodes.forEach((n,i)=>{if(n.cluster===undefined||n.timestamp<renderer.timeRange[0]||n.timestamp>renderer.timeRange[1])return;const c=n.cluster;if(!groups.has(c))groups.set(c,[]);groups.get(c).push(renderer.screen(i))});let count=0;for(const[c,p]of groups){if(p.length<3||count++>100)continue;const hull=convexHull(p);ctx.beginPath();hull.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.fillStyle=`hsla(${c*57%360},55%,65%,.035)`;ctx.strokeStyle=`hsla(${c*57%360},55%,65%,.18)`;ctx.fill();ctx.stroke();}}
 const indices=selected>=0?[selected]:model.nodes.length<1000?model.nodes.map((_,i)=>i).filter(i=>i%27===0):[];ctx.font='10px system-ui';for(const i of indices){const n=model.nodes[i];if(!n||n.timestamp<renderer.timeRange[0]||n.timestamp>renderer.timeRange[1])continue;const[x,y]=renderer.screen(i);ctx.fillStyle=i===selected?'#e3eafa':'#7b92b3';ctx.fillText(n.value.length>34?n.value.slice(0,31)+'…':n.value,x+10,y-9);if(i===selected){ctx.strokeStyle='#c3d7f8';ctx.beginPath();ctx.arc(x,y,12,0,Math.PI*2);ctx.stroke();}}
}
async function choose(i){selected=i;renderer.select(i>=0?[i]:[]);drawOverlay();$('selection').replaceChildren();$('transforms').replaceChildren();if(i<0){$('selection').textContent='Выберите узел.';return}const n=model.nodes[i],id=n.id;const icon=document.createElement('div');icon.className='entity-icon';icon.textContent={domain:'◎',ip:'▦',username:'♙',url:'↗',email:'@'}[n.kind]||'◈';const title=document.createElement('div');title.className='entity-title';title.textContent=n.value;const type=document.createElement('div');type.className='entity-type';type.textContent=n.kind;const confidence=document.createElement('span');confidence.className='confidence';confidence.textContent=n.confidence||'data';$('selection').append(icon,title,type,confidence);const property=(a,b)=>{const row=document.createElement('div');row.className='property';const key=document.createElement('span'),v=document.createElement('span');key.textContent=a;v.textContent=b;row.append(key,v);$('selection').append(row)};property('Источники',(n.sources||[]).join(', ')||'—');property('Наблюдение',new Date(n.timestamp*1000).toISOString().slice(0,10));property('Связи',String(model.edges.reduce((c,e)=>c+Number(e.a===i||e.b===i),0)));if(n.cluster!==undefined)property('Кластер',String(n.cluster));
 const applicable=manifests.filter(m=>m.input===n.kind);if(applicable.length){$('transforms').append(button('Запустить доступные →',()=>run(applicable.map(m=>m.id)),'transform-button'));for(const group of confidenceNames){const list=applicable.filter(m=>m.group===group);if(!list.length)continue;const label=document.createElement('div');label.className='transform-group';label.textContent=group.toUpperCase();$('transforms').append(label);for(const m of list)$('transforms').append(button(m.name+'  ↗',()=>run([m.id]),'transform-button'));}}else{$('transforms').textContent=demo?'Для реальных запросов откройте сохранённое исследование.':'Для этого типа нет подключённых трансформаций.';}
 if(desktop&&!demo){const full=await invoke('node',{id});if(model.nodes[selected]?.id!==id)return;const pre=document.createElement('pre');pre.className='attributes';pre.textContent=JSON.stringify(full?.attributes||{},null,2);$('selection').append(pre);}
}
async function run(sources){if(demo||!desktop){toast('Реальные трансформации доступны в desktop-режиме на сохранённом графе.');return}if(running)throw new Error('Дождитесь текущего задания или отмените его.');const n=model.nodes[selected];if(!n)return;const total=await invoke('run_transforms',{id:n.id,sources});running=true;$('cancel').hidden=false;$('status').textContent=`Запущено ${total} трансформаций`;$('progress').style.width='0%';log(`Старт: ${total} источников`)}
async function loadSaved(){const version=++loadVersion;demo=false;model=new GraphModel();selected=-1;if(desktop){for(const table of ['nodes','edges']){let after=0;while(true){const r=await invoke('page',{table,after});if(version!==loadVersion)return;if(!r.items.length)break;model.merge({nodes:table==='nodes'?r.items:[],edges:table==='edges'?r.items:[]},false);after=r.cursor;}}}model.rebuild();refresh([],true);await choose(-1)}
async function savePositions(){if(!desktop||demo||!model.nodes.length)return;const nodes=model.nodes;for(let i=0;i<nodes.length;i+=256){await invoke('positions',{positions:nodes.slice(i,i+256).map(n=>({id:n.id,x:n.x,y:n.y}))});}}
let polling=false;setInterval(safe(async()=>{if(!desktop||polling)return;polling=true;try{const progress=await invoke('poll_job');const active=[];let changed=false;for(const p of progress){if(p.batch){active.push(...model.merge(p.batch,false));changed=true;}$('progress').style.width=`${p.total?p.done/p.total*100:0}%`;if(p.source)log(`${p.source} · ${p.error||'готово'}`,!!p.error);if(p.status==='finished'||p.status==='cancelled'){running=false;$('cancel').hidden=true;$('status').textContent=p.status==='cancelled'?'Отменено':'Готово';}}if(changed){model.rebuild();refresh(active);}}finally{polling=false}}),150);
setInterval(safe(async()=>{if(!desktop){$('memory').textContent=performance.memory?`JS heap ${(performance.memory.usedJSHeapSize/1048576).toFixed(0)} MiB`:'RAM · измеряется в desktop';return}const s=await invoke('stats');$('memory').textContent=s.backend_rss_bytes?`Backend RSS ${(s.backend_rss_bytes/1048576).toFixed(0)} MiB`:`Graph estimate ${(s.graph_estimated_bytes/1048576).toFixed(0)} MiB`;$('memory').title='Не включает WebView и память GPU';$('cache').textContent=`Cache ${(s.cache_hit_rate*100).toFixed(0)}%`}),2000);
let searchTimer;$('search').addEventListener('input',()=>{clearTimeout(searchTimer);const seq=++searchSeq;searchTimer=setTimeout(safe(async()=>{currentQuery=$('search').value.trim();const ids=!currentQuery?[]:desktop&&!demo?await invoke('search',{query:currentQuery}):model.nodes.filter(n=>JSON.stringify(n).toLowerCase().includes(currentQuery.toLowerCase())).slice(0,500).map(n=>n.id);if(seq!==searchSeq)return;renderer.select(ids.map(id=>model.ids.get(id)).filter(i=>i!==undefined));$('search-count').textContent=currentQuery?`${ids.length} совп.`:'';if(ids.length===1){const i=model.ids.get(ids[0]);renderer.camera=[model.positions[i*2],model.positions[i*2+1]];renderer.dirty=true;}drawOverlay()}),180)});
function applyTime(){const[from,to]=timeRange($('date-from').value,$('date-to').value);renderer.filter(from,to);$('date-label').textContent=Number.isFinite(from)||Number.isFinite(to)?'Фильтр по дате':'Все события';drawOverlay();if(view==='map')drawMap();}
for(const id of ['date-from','date-to'])$(id).onchange=safe(applyTime);$('time-reset').onclick=()=>{$('date-from').value='';$('date-to').value='';applyTime()};
let pointer;const canvas=$('graph');canvas.onpointerdown=e=>{if(e.button!==0)return;pointer={x:e.offsetX,y:e.offsetY,camera:[...renderer.camera],moved:false};canvas.setPointerCapture(e.pointerId);$('context').hidden=true};canvas.onpointermove=e=>{if(!pointer)return;const dx=e.offsetX-pointer.x,dy=e.offsetY-pointer.y;if(Math.abs(dx)+Math.abs(dy)>4)pointer.moved=true;renderer.camera=[pointer.camera[0]-dx/renderer.zoom,pointer.camera[1]-dy/renderer.zoom];renderer.dirty=true;drawOverlay()};canvas.onpointerup=safe(async e=>{if(pointer&&!pointer.moved)await choose(renderer.pick(e.offsetX,e.offsetY));pointer=null});canvas.onpointercancel=()=>pointer=null;canvas.onwheel=e=>{e.preventDefault();renderer.zoom=Math.max(.03,Math.min(50,renderer.zoom*Math.exp(-e.deltaY*.001)));renderer.dirty=true;drawOverlay()};canvas.addEventListener('wheel',()=>{},{passive:false});canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.oncontextmenu=safe(async e=>{e.preventDefault();const i=renderer.pick(e.offsetX,e.offsetY);if(i<0)return;await choose(i);const menu=$('context');menu.replaceChildren();const title=document.createElement('p');title.className='muted';title.textContent='ТРАНСФОРМАЦИИ · DATA';menu.append(title);const list=manifests.filter(m=>m.input===model.nodes[i].kind);for(const m of list)menu.append(button(m.name,()=>{menu.hidden=true;return run([m.id])}));if(!list.length)menu.append(document.createTextNode('Нет доступных трансформаций'));menu.style.left=Math.min(e.offsetX,renderer.width-260)+'px';menu.style.top=Math.min(e.offsetY,renderer.height-300)+'px';menu.hidden=false});document.addEventListener('pointerdown',e=>{if(!$('context').contains(e.target))$('context').hidden=true});
$('fit').onclick=()=>{renderer.fit();drawOverlay()};$('zoom-in').onclick=()=>{renderer.zoom*=1.25;renderer.dirty=true;drawOverlay()};$('zoom-out').onclick=()=>{renderer.zoom/=1.25;renderer.dirty=true;drawOverlay()};$('layout').onclick=()=>{if(!model.nodes.length)return;renderer.startLayout();log('GPU: локальная релаксация, 100 итераций')};
$('cluster').onclick=safe(async()=>{if(!model.nodes.length)return;if(worker){worker.terminate();worker=null;$('cluster').textContent='Кластеры';return}const version=++clusterVersion,graph=model,revision=model.revision;$('cluster').textContent='Отмена расчёта';worker=new Worker('./community.js',{type:'module'});worker.onmessage=e=>{worker?.terminate();worker=null;$('cluster').textContent='Кластеры';if(version!==clusterVersion||model!==graph||model.revision!==revision)return;if(e.data.error){toast(e.data.error);return}e.data.labels.forEach((c,i)=>model.nodes[i].cluster=c);hulls=true;drawOverlay();log(`Louvain · ${new Set(e.data.labels).size} сообществ`)};worker.onerror=e=>{toast(e.message);worker?.terminate();worker=null;$('cluster').textContent='Кластеры'};const links=model.links.slice();worker.postMessage({count:model.nodes.length,links},[links.buffer]);});
function openAdd(){if(demo)toast('Новая сущность будет добавлена в сохранённое исследование.');$('add-dialog').showModal();$('node-value').focus()}
$('add').onclick=openAdd;$('empty-add').onclick=openAdd;$('add-form').onsubmit=safe(async e=>{e.preventDefault();const kind=$('node-kind').value,value=$('node-value').value.trim();if(!value)throw new Error('Введите значение');if(demo)await loadSaved();const batch=desktop?await invoke('add_node',{kind,value}):{nodes:[{id:crypto.randomUUID(),kind,value,confidence:'data',sources:['analyst'],timestamp:Date.now()/1000,x:0,y:0}],edges:[]};model.merge(batch);refresh([],true);$('add-dialog').close();$('node-value').value='';await choose(model.ids.get(batch.nodes[0].id))});
// Prevent native form navigation immediately, before the async wrapper runs.
for(const id of ['add-form','settings-form','vault-form'])$(id).addEventListener('submit',e=>e.preventDefault());
for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>b.closest('dialog').close();
$('demo').onclick=()=>{if(running){toast('Сначала завершите текущее задание.');return}$('demo-dialog').showModal()};$('empty-demo').onclick=$('demo').onclick;$('demo-load').onclick=safe(async()=>{$('demo-dialog').close();$('status').textContent='Создание примера…';await new Promise(r=>setTimeout(r,20));demo=true;loadVersion++;model=synthetic(Number($('demo-size').value));hulls=model.nodes.length<1000;selected=-1;refresh([],true);$('status').textContent='Синтетический граф';renderer.continuous=model.nodes.length>=50000;await choose(0);log(`Пример · ${model.nodes.length.toLocaleString()} узлов / ${model.edges.length.toLocaleString()} рёбер`)});
$('settings').onclick=()=>{const r=config.network.default_route;$('route-mode').value=r.mode;$('proxy-url').value=r.url||'';$('resolver').value=r.resolver||'cloudflare';$('source-routes').value=JSON.stringify(config.network.sources||{},null,2);$('memory-budget').value=config.memory_mb;$('settings-dialog').showModal()};$('settings-form').onsubmit=safe(async()=>{if(!desktop)throw new Error('Настройки сети доступны в desktop-сборке.');const mode=$('route-mode').value,route=mode==='proxy'?{mode,url:$('proxy-url').value}:mode==='direct_doh'?{mode,resolver:$('resolver').value}:{mode};const c={memory_mb:Number($('memory-budget').value),network:{anonymous:mode!=='direct_doh',default_route:route,sources:JSON.parse($('source-routes').value)}};await invoke('configure',{config:c});config=c;routeBadge();$('settings-dialog').close();toast('Настройки сохранены')});
function routeBadge(){$('route-badge').textContent='● '+config.network.default_route.mode.toUpperCase()}
$('cancel').onclick=safe(()=>invoke('cancel_job'));
$('vault-form').onsubmit=safe(async()=>{if(!desktop)throw new Error('Хранилище ключей доступно в desktop-сборке.');const args={source:$('key-source').value,key:$('api-key').value,passphrase:$('passphrase').value};$('api-key').value='';$('passphrase').value='';await invoke('vault_save',args);toast('Ключ зашифрован локально')});$('vault-lock').onclick=safe(async()=>{if(!desktop)return;await invoke('vault_lock');$('api-key').value='';$('passphrase').value='';toast('Ключи удалены из памяти хранилища')});$('vault-unlock').onclick=safe(async()=>{if(!desktop)return;const passphrase=$('passphrase').value;$('passphrase').value='';await invoke('vault_unlock',{passphrase});toast('Хранилище разблокировано')});
$('export').onclick=()=>$('export-dialog').showModal();$('export-save').onclick=safe(async()=>{const format=$('export-format').value;if(desktop&&!demo){await savePositions();const path=await invoke('export_graph',{format});toast(`Сохранено: ${path}`)}else{if(format!=='json')throw new Error('В браузерном примере доступен JSON; остальные форматы реализованы в Rust.');const edges=model.edges.map(e=>({id:e.id,source:model.nodes[e.a].id,target:model.nodes[e.b].id,relation:'synthetic',provenance:'fixture',timestamp:model.nodes[e.a].timestamp}));const blob=new Blob([JSON.stringify({version:1,synthetic:demo,nodes:model.nodes,edges})],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='linkscope-graph.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}$('export-dialog').close()});
function drawMap(){const canvas=$('map'),r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,1.5);canvas.width=r.width*d;canvas.height=r.height*d;const c=canvas.getContext('2d');c.scale(d,d);c.fillStyle='#0c1420';c.fillRect(0,0,r.width,r.height);c.strokeStyle='#223147';c.lineWidth=1;for(let lng=-180;lng<=180;lng+=30){const x=(lng+180)/360*r.width;c.beginPath();c.moveTo(x,0);c.lineTo(x,r.height);c.stroke()}for(let lat=-90;lat<=90;lat+=30){const y=(90-lat)/180*r.height;c.beginPath();c.moveTo(0,y);c.lineTo(r.width,y);c.stroke()}let count=0;for(const n of model.nodes){const geo=n.geo;if(!geo||n.timestamp<renderer.timeRange[0]||n.timestamp>renderer.timeRange[1])continue;c.fillStyle='#80b5e8';c.beginPath();c.arc((geo.lon+180)/360*r.width,(90-geo.lat)/180*r.height,4,0,Math.PI*2);c.fill();count++}c.fillStyle='#8ba2be';c.font='13px system-ui';c.fillText(count?`${count} координат · equirectangular projection`:'Нет координат. Офлайн-сетка широты/долготы; геоданные не выводятся из IP автоматически.',25,r.height/2)}
$('map-tab').onclick=()=>{view='map';$('map').hidden=false;$('graph-tab').classList.remove('active');$('map-tab').classList.add('active');drawMap()};$('graph-tab').onclick=()=>{view='graph';$('map').hidden=true;$('map-tab').classList.remove('active');$('graph-tab').classList.add('active');renderer.dirty=true};window.addEventListener('resize',()=>{drawOverlay();if(view==='map')drawMap()});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();$('search').focus()}if(e.key==='Escape')$('context').hidden=true});
await safe(async()=>{if(desktop){const r=await invoke('info');manifests=r.transforms;config=r.config;$('status').textContent=r.ephemeral?'Ephemeral · RAM only':'Готово';routeBadge();await loadSaved()}else{updateCounts();renderer.resize();$('status').textContent='Браузерный просмотр · без Rust backend';}})();
if(renderer.disabled){$('status').textContent='Граф недоступен · безопасный режим';$('graph-note').textContent='GPU недоступен · безопасный режим'}
// Read-only handles for reproducible renderer tests; no privileged methods exposed.
window.linkscope={get model(){return model},get renderer(){return renderer},get mode(){return demo?'demo':desktop?'desktop':'browser'}};
