import {colors,confidenceNames} from './model.js';
const vertex=`#version 300 es
precision highp float;
in vec2 position;in vec3 color;in float confidence;in float timestamp;in float selected;
uniform vec2 resolution;uniform vec2 camera;uniform float zoom;uniform float dpr;uniform float pointSize;uniform vec2 timeRange;uniform bool edges;
out vec3 vColor;out float vConfidence;out float vSelected;out float vVisible;
void main(){vec2 p=(position-camera)*zoom;gl_Position=vec4(p/resolution*2.0*vec2(1.,-1.),0.,1.);gl_PointSize=pointSize*dpr;vColor=color;vConfidence=confidence;vSelected=selected;vVisible=float(timestamp>=timeRange.x&&timestamp<=timeRange.y);if(vVisible<.5&&!edges)gl_Position=vec4(3.,3.,0.,1.);}`;
const fragment=`#version 300 es
precision highp float;
in vec3 vColor;in float vConfidence;in float vSelected;in float vVisible;uniform bool edges;out vec4 outColor;
void main(){if(vVisible<.999)discard;if(edges){outColor=vec4(.31,.43,.61,.12);return;}float r=length(gl_PointCoord-.5)*2.;if(r>1.)discard;vec3 ring=vConfidence<.5?vec3(.42,.6,.99):vConfidence<1.5?vec3(.38,.78,.67):vConfidence<2.5?vec3(.72,.58,.98):vec3(.96,.54,.54);if(vSelected>.5)ring=vec3(1.,.94,.66);outColor=vec4(r>.67?ring:vColor*.5,1.);}`;
const layoutVS=`#version 300 es
precision highp float;precision highp int;in vec2 position;in float isActive;uniform sampler2D positions;uniform sampler2D neighbors;uniform int width;uniform int count;out vec2 nextPosition;
vec2 pos(int id){return texelFetch(positions,ivec2(id%width,id/width),0).xy;}
void main(){int id=gl_VertexID;if(isActive<.5){nextPosition=position;return;}vec4 ids=texelFetch(neighbors,ivec2(id%width,id/width),0);vec2 force=vec2(0.);for(int k=0;k<4;k++){int j=int(ids[k]);if(j>=0){vec2 d=pos(j)-position;float dist=max(length(d),.01);force+=d/dist*(dist-35.)*.007;}}for(int k=1;k<=8;k++){int j=(id*13+k*7919)%count;if(j==id)continue;vec2 d=position-pos(j);float d2=max(dot(d,d),4.);force+=d/d2*8.;}float f=length(force);nextPosition=position+force/max(1.,f/2.);}`;
function program(gl,vs,fs,feedback){const p=gl.createProgram();for(const[type,src]of[[gl.VERTEX_SHADER,vs],[gl.FRAGMENT_SHADER,fs]]){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));gl.attachShader(p,s);gl.deleteShader(s)}if(feedback)gl.transformFeedbackVaryings(p,feedback,gl.INTERLEAVED_ATTRIBS);gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p));return p;}
export class Renderer{
 constructor(canvas,onFrame){this.canvas=canvas;this.gl=canvas.getContext('webgl2',{alpha:false,antialias:false,preserveDrawingBuffer:false,powerPreference:'high-performance'});if(!this.gl)throw new Error('Требуется WebGL2. Проверьте аппаратное ускорение WebView.');const g=this.gl;this.drawProgram=program(g,vertex,fragment);this.layoutProgram=program(g,layoutVS,'#version 300 es\nprecision highp float;out vec4 c;void main(){c=vec4(0.);}', ['nextPosition']);this.camera=[0,0];this.zoom=1;this.timeRange=[-1e20,1e20];this.buffers=[];this.textures=[];this.layoutSteps=0;this.frames=0;this.frameStart=performance.now();this.onFrame=onFrame;this.dirty=true;this.continuous=false;this.lost=false;canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();this.lost=true;this.onFrame?.({error:'WebGL context lost — перезапустите просмотр'});});canvas.addEventListener('webglcontextrestored',()=>location.reload());this.observer=new ResizeObserver(()=>{this.resize();this.dirty=true});this.observer.observe(canvas);this.tick=this.tick.bind(this);requestAnimationFrame(this.tick);}
 resize(){this.dpr=Math.min(devicePixelRatio||1,1.5);const r=this.canvas.getBoundingClientRect();this.width=r.width;this.height=r.height;this.canvas.width=Math.max(1,Math.round(r.width*this.dpr));this.canvas.height=Math.max(1,Math.round(r.height*this.dpr));}
 buffer(data,target=this.gl.ARRAY_BUFFER){const g=this.gl,b=g.createBuffer();this.buffers.push(b);g.bindBuffer(target,b);g.bufferData(target,data,g.DYNAMIC_DRAW);return b}
 texture(data,format,internal){const g=this.gl,t=g.createTexture();this.textures.push(t);g.bindTexture(g.TEXTURE_2D,t);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MIN_FILTER,g.NEAREST);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MAG_FILTER,g.NEAREST);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_S,g.CLAMP_TO_EDGE);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_T,g.CLAMP_TO_EDGE);g.texImage2D(g.TEXTURE_2D,0,internal,this.texWidth,this.texHeight,0,format,g.FLOAT,data);return t}
 setModel(model,activeIndices=[]){const g=this.gl;for(const b of this.buffers)g.deleteBuffer(b);for(const t of this.textures)g.deleteTexture(t);this.buffers=[];this.textures=[];this.model=model;this.count=model.nodes.length;this.texWidth=Math.min(2048,g.getParameter(g.MAX_TEXTURE_SIZE));this.texHeight=Math.max(1,Math.ceil(this.count/this.texWidth));const padded=this.texWidth*this.texHeight;const p=new Float32Array(padded*2);p.set(model.positions);this.posBuffers=[this.buffer(p),this.buffer(p)];this.front=0;this.positionTexture=this.texture(p,g.RG,g.RG32F);const neighbors=new Float32Array(padded*4).fill(-1),degree=new Uint8Array(this.count);for(const e of model.edges){if(degree[e.a]<4)neighbors[e.a*4+degree[e.a]++]=e.b;if(degree[e.b]<4)neighbors[e.b*4+degree[e.b]++]=e.a;}this.neighborTexture=this.texture(neighbors,g.RGBA,g.RGBA32F);this.active=new Float32Array(this.count);for(const i of activeIndices)this.active[i]=1;this.activeBuffer=this.buffer(this.active);this.metadata=new Float32Array(this.count*6);model.nodes.forEach((n,i)=>{this.metadata.set(colors[n.kind]||colors.domain,i*6);this.metadata[i*6+3]=Math.max(0,confidenceNames.indexOf(n.confidence));this.metadata[i*6+4]=n.timestamp;});this.metaBuffer=this.buffer(this.metadata);this.edgeBuffer=this.buffer(model.links,g.ELEMENT_ARRAY_BUFFER);this.edgeCount=model.links.length;this.layoutSteps=activeIndices.length?30:0;this.dirty=true;}
 attrib(p,name,buffer,size,stride=0,offset=0){const g=this.gl,i=g.getAttribLocation(p,name);if(i<0)return;g.bindBuffer(g.ARRAY_BUFFER,buffer);g.enableVertexAttribArray(i);g.vertexAttribPointer(i,size,g.FLOAT,false,stride,offset);}
 uniform(p,n,method,...args){const g=this.gl;g[method](g.getUniformLocation(p,n),...args)}
 select(indices){if(!this.metadata)return;for(let i=0;i<this.count;i++)this.metadata[i*6+5]=0;for(const i of indices)if(i>=0&&i<this.count)this.metadata[i*6+5]=1;const g=this.gl;g.bindBuffer(g.ARRAY_BUFFER,this.metaBuffer);g.bufferSubData(g.ARRAY_BUFFER,0,this.metadata);this.dirty=true;}
 filter(from,to){this.timeRange=[Number.isFinite(from)?from:-1e20,Number.isFinite(to)?to:1e20];const indices=[];for(const e of this.model?.edges||[]){const a=this.model.nodes[e.a].timestamp,b=this.model.nodes[e.b].timestamp;if(a>=from&&a<=to&&b>=from&&b<=to)indices.push(e.a,e.b)}const g=this.gl;if(this.edgeBuffer){g.bindBuffer(g.ELEMENT_ARRAY_BUFFER,this.edgeBuffer);g.bufferData(g.ELEMENT_ARRAY_BUFFER,new Uint32Array(indices),g.DYNAMIC_DRAW);this.edgeCount=indices.length}this.dirty=true;}
 fit(){if(!this.count)return;let minx=Infinity,miny=Infinity,maxx=-Infinity,maxy=-Infinity;for(let i=0;i<this.model.positions.length;i+=2){minx=Math.min(minx,this.model.positions[i]);maxx=Math.max(maxx,this.model.positions[i]);miny=Math.min(miny,this.model.positions[i+1]);maxy=Math.max(maxy,this.model.positions[i+1]);}this.camera=[(minx+maxx)/2,(miny+maxy)/2];this.zoom=Math.min(this.width/(maxx-minx+130),this.height/(maxy-miny+130));this.dirty=true;}
 step(){const g=this.gl,p=this.layoutProgram;g.useProgram(p);this.attrib(p,'position',this.posBuffers[this.front],2);this.attrib(p,'isActive',this.activeBuffer,1);g.activeTexture(g.TEXTURE0);g.bindTexture(g.TEXTURE_2D,this.positionTexture);this.uniform(p,'positions','uniform1i',0);g.activeTexture(g.TEXTURE1);g.bindTexture(g.TEXTURE_2D,this.neighborTexture);this.uniform(p,'neighbors','uniform1i',1);this.uniform(p,'width','uniform1i',this.texWidth);this.uniform(p,'count','uniform1i',this.count);g.bindBufferBase(g.TRANSFORM_FEEDBACK_BUFFER,0,this.posBuffers[1-this.front]);g.enable(g.RASTERIZER_DISCARD);g.beginTransformFeedback(g.POINTS);g.drawArrays(g.POINTS,0,this.count);g.endTransformFeedback();g.disable(g.RASTERIZER_DISCARD);g.bindBufferBase(g.TRANSFORM_FEEDBACK_BUFFER,0,null);this.front=1-this.front;g.activeTexture(g.TEXTURE0);g.bindTexture(g.TEXTURE_2D,this.positionTexture);g.bindBuffer(g.PIXEL_UNPACK_BUFFER,this.posBuffers[this.front]);g.texSubImage2D(g.TEXTURE_2D,0,0,0,this.texWidth,this.texHeight,g.RG,g.FLOAT,0);g.bindBuffer(g.PIXEL_UNPACK_BUFFER,null);}
 readPositions(){if(!this.model)return;const g=this.gl,p=new Float32Array(this.count*2);g.bindBuffer(g.ARRAY_BUFFER,this.posBuffers[this.front]);g.getBufferSubData(g.ARRAY_BUFFER,0,p);this.model.setPositions(p);}
 startLayout(indices){if(!this.count)return;this.active.fill(indices?0:1);for(const i of indices||[])this.active[i]=1;const g=this.gl;g.bindBuffer(g.ARRAY_BUFFER,this.activeBuffer);g.bufferSubData(g.ARRAY_BUFFER,0,this.active);this.layoutSteps=100;this.dirty=true;}
 draw(){const g=this.gl,p=this.drawProgram;g.viewport(0,0,this.canvas.width,this.canvas.height);g.clearColor(.047,.071,.106,1);g.clear(g.COLOR_BUFFER_BIT);if(!this.count)return;g.useProgram(p);this.attrib(p,'position',this.posBuffers[this.front],2);this.attrib(p,'color',this.metaBuffer,3,24,0);this.attrib(p,'confidence',this.metaBuffer,1,24,12);this.attrib(p,'timestamp',this.metaBuffer,1,24,16);this.attrib(p,'selected',this.metaBuffer,1,24,20);this.uniform(p,'resolution','uniform2f',this.width,this.height);this.uniform(p,'camera','uniform2fv',this.camera);this.uniform(p,'zoom','uniform1f',this.zoom);this.uniform(p,'dpr','uniform1f',this.dpr);this.uniform(p,'timeRange','uniform2fv',this.timeRange);g.enable(g.BLEND);g.blendFunc(g.SRC_ALPHA,g.ONE_MINUS_SRC_ALPHA);this.uniform(p,'edges','uniform1i',1);g.bindBuffer(g.ELEMENT_ARRAY_BUFFER,this.edgeBuffer);g.drawElements(g.LINES,this.edgeCount,g.UNSIGNED_INT,0);this.uniform(p,'edges','uniform1i',0);this.uniform(p,'pointSize','uniform1f',this.count>5000?3:9);g.drawArrays(g.POINTS,0,this.count);g.disable(g.BLEND);}
 tick(t){if(this.lost)return;let drew=false;if(this.layoutSteps>0&&this.count){this.step();this.layoutSteps--;this.dirty=true;if(this.layoutSteps===0){this.readPositions();this.onFrame?.({layoutDone:true});}}if(this.dirty||this.continuous){this.draw();this.dirty=false;this.frames++;drew=true;}if(t-this.frameStart>=1000){this.onFrame?.({fps:this.frames*1000/(t-this.frameStart),idle:!drew&&!this.continuous});this.frames=0;this.frameStart=t;}requestAnimationFrame(this.tick)}
 screen(i){return[(this.model.positions[i*2]-this.camera[0])*this.zoom+this.width/2,(this.model.positions[i*2+1]-this.camera[1])*this.zoom+this.height/2]}
 pick(x,y){if(this.layoutSteps>0)this.readPositions();let best=-1,dist=144;for(let i=0;i<this.count;i++){const n=this.model.nodes[i];if(n.timestamp<this.timeRange[0]||n.timestamp>this.timeRange[1])continue;const[sx,sy]=this.screen(i),d=(sx-x)**2+(sy-y)**2;if(d<dist){dist=d;best=i}}return best}
}
